version: '2'

services:

    web:
        container_name: myweb_web
        command: gunicorn -w 4 -b 0.0.0.0:5000 -t 160 run:app
        build: ./myweb
        ports:
            - "30011:5000"
        volumes:
            - ./myweb:/home/hxh/myweb
        links:
            - mongo
        depends_on:
            - mongo

    mongo:
        container_name: myweb_mongo
        image: mongo
        restart: always
        ports:
            - '27018:27017'