#coding:utf8

WEB_NAME = 'myweb'

WXAPP_ID = None
WXAPP_SECRET = None

TOKEN_SECRET_KEY = 'xxx'
TOKEN_SALT = 'xxx'
TOKEN_TIMEOUT_HOURS = 24 * 365
TOKEN_FIELDS_REQUIRED = ['openid']

TOKEN_HEADER_FIELD = 'token'
LOGIN_CODE_FIELD_NAME = 'code'
UPDATE_IV_FIELD_NAME = 'iv'
UPDATE_ENCRYPTEDDATA_FIELD_NAME = 'encryptedData'

bp = None
api = None